### ISSUE TITLE
Labels zeroed with defernumbers, nocite and entries added later

### ISSUE THREAD

**Issue by moewew** [plk/biblatex#1067]
From https://tex.stackexchange.com/q/567770/35864

The MWE needs a two-step process.

Compile first
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, defernumbers=true]{biblatex}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \nocite{*}

\printbibliography
\end{document}
```
with only one entry in the `.bib` file.

Then add a new entry to the `.bib` file and recompile.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, defernumbers=true]{biblatex}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
@book{belk,
  author    = {Anne Belk},
  title     = {A Theory on Brontosauruses},
  year      = {1980},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
Lorem \nocite{*}

\printbibliography
\end{document}
```
Unless the `.aux` file is cleaned between the two compile steps, the new entry will be marked as [0].

![[0] Anne Belk. A Theory on Brontosauruses. London: Monthy & Co., 1980.](https://user-images.githubusercontent.com/6755835/96965410-67313100-150c-11eb-8373-b173dbb7a89d.png)

**Comment by plk** [comment]
This only happens with `\nocite`, looking into it.

**Comment by moewew** [comment]
https://github.com/plk/biblatex/commit/4615549ee338e6f04aa3b8a5ea56df73e93a68c4 fixed this issue here, but there still seems to be an issue with the example from https://tex.stackexchange.com/q/567770/35864. I'll investigate and see if I can come up with an MWE.

**Comment by moewew** [comment]
MWE. This is basically the reverse of the above.

Run first
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, defernumbers=true]{biblatex}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
@book{belk,
  author    = {Anne Belk},
  title     = {A Theory on Brontosauruses},
  year      = {1980},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\printbibliography
\nocite{*}
\end{document}
```
then remove the first bibliography entry from the `.bib` file
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, defernumbers=true]{biblatex}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\printbibliography
\nocite{*}
\end{document}
```
The reference number shows as 2


![\[2\] Anne Elk. A Theory on Brontosauruses. London: Monthy & Co., 1972.](https://user-images.githubusercontent.com/6755835/99151602-b64a2c00-269c-11eb-8040-7044cbd22e7d.png)

**Comment by plk** [comment]
Should be fixed for both cases now I believe.

**Comment by moewew** [comment]
The second MWE still gives me \[2\] for the only reference in the bibliography at the end.

**Comment by plk** [comment]
Strange, I'm sure it was working last night ... checking again.

**Comment by moewew** [comment]
I had another look at the second MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, defernumbers=true]{biblatex}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
@book{belk,
  author    = {Anne Belk},
  title     = {A Theory on Brontosauruses},
  year      = {1980},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\printbibliography
\nocite{*}
\end{document}
```
then remove the first bibliography entry from the `.bib` file
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=numeric, defernumbers=true]{biblatex}

\begin{filecontents}[overwrite]{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\printbibliography
\nocite{*}
\end{document}
```
and still get the 2 in the output
![\[2\] Anne Elk. A Theory on Brontosauruses. London: Monthy & Co., 1972.](https://user-images.githubusercontent.com/6755835/99151602-b64a2c00-269c-11eb-8040-7044cbd22e7d.png)
While the new tests in https://github.com/plk/biblatex/commit/a9a23778ff7685210acc80805832fa221e4ad8b1 seem to trigger the LaTeX rerun requests in the correct cases, this rerun doesn't actually change the numbering. The `.aux` file still has
```latex
\abx@aux@number{0}{elk}{0}{nty/global//global/global}{2}
```
no matter how often I rerun LaTeX.

**Comment by plk** [comment]
I see what's going on. It's a strange issue with order. In your examples, there is:

```
\printbibliography
\nocite{*}
```

but I semi-consciously corrected this when pasting to:

```
\nocite{*}
\printbibliography
```

I wouldn't expect the former to work as the position of `\printbibliography` determines default refcontexts which has a lot of effects ...

**Comment by moewew** [comment]
I certainly agree that `\nocite{*}` after `\printbibliography` is unusual (and I, too, changed the order when I worked with the example from https://tex.stackexchange.com/q/567770/35864, it took me a bit to figure out the issue), but I really think this should work. In general I have not experienced any issues with `\cite` or `\nocite` after `\printbibliography`. Especially since `\nocite{*}` can be used in the preamble as well I expect it to work anywhere in the document.

**Comment by plk** [comment]
That's a good point about `\nocite{*}` in preamble. Have to have a look at this.

**Comment by plk** [comment]
Both examples work for me now with the latest patch. Needs `.aux` support for `\nocite{*}` after `\printbibliography` as printing bibitems relies on knowing whether `\nocite{*}` was present. `\nocite{*}` in preamble was fine.

**Comment by moewew** [comment]
Yup, the examples work well now and so does the MWE from https://tex.stackexchange.com/q/567770/35864.
