### ISSUE TITLE
Split bibliographies at the begin of the document

### ISSUE THREAD

**Issue by u-fischer** [plk/biblatex#179]
I tried to print a splitted bibliography at the begin of a document. On things I tried was 
````
\documentclass{book}
\usepackage[utf8]{inputenc}
\usepackage[defernumbers]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}

\printbibliography[segment=1,sorting=none,resetnumbers]
\printbibliography[segment=2,sorting=none,resetnumbers]

\newrefsegment
\cite{angenendt} \cite{baez/article} \cite{doody}

\newrefsegment
\cite{gillies} \cite{doody} \cite{angenendt} \cite{baez/article}

\end{document}
````
But this gave the error

      ! Package biblatex Error: Segment '1' not found in section '0'.

From the documentation I can't decide if this is a bug or simply not meant to work. I also asked on stackexchange but without a definite answer
http://tex.stackexchange.com/q/141163/2388

Ulrike Fischer

**Comment by plk** [comment]
Re-opening as it's related to #406. This should now work with the latest biblatex 3.4/biber 2.5 dev versions.

**Comment by moewew** [comment]
Interestingly, in Ulrike's example from above, `gillies` gets "[1]" in the second bibliography and is still sorted at the end. I removed `sorting=none` from the `\printbibliography` calls

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[defernumbers=true,backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
\printbibliography[segment=1,resetnumbers]
\printbibliography[segment=2,resetnumbers]

\newrefsegment
\cite{angenendt} \cite{baez/article} \cite{doody}

\newrefsegment
\cite{gillies} \cite{doody} \cite{angenendt} \cite{baez/article}
\end{document}
```

The first bibliography is
> [1] angenendt
[2] baez/article
[3] doody

the second is
>[1] angenendt
[2] baez/article
[3] doody
[1] gillies


Even if I do the sensible thing and place the `\printbibliogarphy`s at the end, I still get the weird numbering for `gillies`.

**Comment by plk** [comment]
Hmm, at least it's now equally broken nomatter where the `\printbibliographies` go ... looking into it.

**Comment by moewew** [comment]
I believe this behaviour (at least if one places the bibliography at the end) has been with us for a long time and is not new. To be honest, I don't even know what one should expect. Since we have `resetnumbers` in the MWE, maybe `refsection` would be the better choice anyway.

**Comment by plk** [comment]
It is very tricky because `defernums` is a global option and like most global options, that means global modulo refsections. What this example is essentially requesting is a global numbering in the (one) refsection but then not global across refsegments. This probably shouldn't work because part of the point of refsection vs refsegment is global vs non-global ...

**Comment by plk** [comment]
In fact, if you remove both `resetnumbers`, it works fine with the `\printbibliography`s at either end of the document.

**Comment by plk** [comment]
In fact, if you remove both `resetnumbers`, it works fine with the `\printbibliography`s at either end of the document.

**Comment by moewew** [comment]
I don't quite understand what the MWE should produce anyway. I suppose it is a simplification of a more complex use case where these kind of troubles didn't appear.

I *think* the code above in a way *emulates* refsections using refsegments.

**Comment by plk** [comment]
Unless @u-fischer has any pertinent comments, I suggest we close this.

**Comment by u-fischer** [comment]
I have absolutly no idea why I used resetnumbers more than two years ago, but in the view of more experience with many bibliographies I agree that the option doesn't make sense here.
