### ISSUE TITLE
Biblatex won't print more than one refcontext bibliography

### ISSUE THREAD

**Issue by logological** [plk/biblatex#655]
I just upgraded to Biblatex 3.8a/Biber 2.8.  I have documents that contain a main bibliography, plus several other bibliographies in their own `refcontext` and `refsection` environments.  Previous versions of Biblatex+Biber dealt with this just fine.  But in the current version, the second and subsequent `refcontext` bibliographies are ignored.  Nothing gets printed by `\printbibliography` (not even the header).  The LaTeX console complains about a missing citation and tells me to rerun Biber, but Biber doesn't complain.  Minimal example:

```
\documentclass{article}
\usepackage{biblatex}
\addbibresource{\jobname.bib}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@inproceedings{foo,
  author       = {Foo},
  title        = {Foo},
  booktitle    = {Foo},
  year         = {2017},
}
\end{filecontents}

\begin{document}

\nocite{foo}\printbibliography

\begin{refcontext}[sorting=ydnt]
\begin{refsection}{}
\nocite{foo}\printbibliography
\end{refsection}
\end{refcontext}

% This prints with older versions of Biblatex+Biber but not the current version
\begin{refcontext}[sorting=ydnt]
\begin{refsection}{}
\nocite{foo}\printbibliography
\end{refsection}
\end{refcontext}

\end{document}
```

Console warnings from pdflatex:

```
LaTeX Warning: Overwriting file `./foo.bib'.
LaTeX Warning: Citation 'foo' undefined on input line 28.
LaTeX Warning: Empty bibliography on input line 28.
LaTeX Warning: There were undefined references.
Package biblatex Warning: Please (re)run Biber on the file:
```

**Comment by moewew** [comment]
Thank you for reporting this.

@plk I think I have chased this down to
https://github.com/plk/biblatex/blob/e707a19c5b9a75ae5724c8e4c1fe0a41e9dd937a/tex/latex/biblatex/biblatex.sty#L7835-L7840
and
https://github.com/plk/biblatex/blob/e707a19c5b9a75ae5724c8e4c1fe0a41e9dd937a/tex/latex/biblatex/biblatex.sty#L8248-L8253
The duplicate checking is a bit too eager, as it will suppress writing out `\blx@xml@dlist`s that are the same across different refsections. This results in a mismatch between the refcontext as reported in the document and the refcontext in the `.bbl`.
The commit that introduced the duplicate checking was https://github.com/plk/biblatex/commit/cebc9bf6d1783931285a4374270cf17d45e36b2c

**Comment by plk** [comment]
Quite right, my test file for this missed this. This is fixed on the master branch in Git and we will release biblatex 3.9 shortly along with biber 2.9. @moewew - are there any other fixes you need to make in biblatex? If so, please apply them to the master branch directly as this will allow us to release without the ISO8601 changes.

**Comment by moewew** [comment]
I will have to merge the fix for totalpages and we could also merge the French localisation updates. Let me try to do that without messing up git. Not sure if I can get it done before tonight though.

**Comment by plk** [comment]
We just have to do it on the master branch. If you are concerned, you can mail me patches and I can apply etc.

**Comment by moewew** [comment]
Let me see how far I can get. If I get stuck I'll call for help.

**Comment by moewew** [comment]
OK, I think I merged what we need without breaking anything. I renamed the changes file to `CHANGES.md` as on `dev`, so you might have to modify the build script.

**Comment by plk** [comment]
@moewew - Looks fineI have updated the build script. I will run tests and initiate releases later today.

**Comment by moewew** [comment]
@logological `biblatex` 3.9 and Biber 2.9 have been released to CTAN and are already in TeX live and MikTeX. Please test if the update fixed things for you.

**Comment by logological** [comment]
With Biblatex 3.9 and Biber 2.9, the behaviour is inconsistent.  The problem is still reproducible for me in my MWE.  In my actual document, I do see all my `refcontext` bibliographies now, but they aren't printing correctly.  In particular:

- The sorting order is wrong.
- All entries from two of the `.bib` files that I've added with `\addbibresource` (but not the others) don't print the months for the entries.  In Biber's console output, I get lots of warnings like the following:
```
WARN - BibTeX subsystem: /tmp/HK5kCG773d/thesis.bib_22617.utf8, line 2714, warning: undefined macro "jan"
WARN - BibTeX subsystem: /tmp/HK5kCG773d/thesis.bib_22617.utf8, line 2723, warning: undefined macro "sep"
WARN - BibTeX subsystem: /tmp/HK5kCG773d/thesis.bib_22617.utf8, line 2735, warning: undefined macro "jun"
```

**Comment by moewew** [comment]
Mhhh. When I ran your MWE from your first post here with `biblatex` 3,9/Biebr 2.9 I got three separate bibliographies, all with the foo entry. What do you get?

Can you make a new MWE that reproduces the wrong sorting order in your actual document? How did you specify the `month`?

**Comment by moewew** [comment]
I could reproduce the month issue and opened https://github.com/plk/biber/issues/199 about that.

But for the other issues an MWE is still needed. You can make bit easier for us to investigate what is going on by also uploading the resulting `.bbl` file.

**Comment by logological** [comment]
I am guessing that the sort issue is just a consequence of the month issue.  I was using a chronological sort, and it's only the ordering of publications within a year that is affected.

Regarding the other issue, see the attached output from runs on the MWE above:

- [console output from pdflatex and biber](https://github.com/plk/biblatex/files/1509433/typescript.txt)
- [foo.bbl](https://github.com/plk/biblatex/files/1509435/foo.bbl.txt)
- screenshot of generated PDF: 
![foo](https://user-images.githubusercontent.com/831326/33315271-8609f302-d430-11e7-86d4-e6c40c0c83d0.png)

**Comment by moewew** [comment]
Can you check that `biblatex` is really at version 3.9?

**Comment by logological** [comment]
Oh, from examining the console output I saw this line:
```
(/opt/texlive/2017/texmf-dist/tex/latex/base/size10.clo)) (./biblatex.sty
```
Looks like I had an old `biblatex.sty` in my current directory, so pdflatex was loading that one instead of the one I had installed system-wide from CTAN.  If I remove the file from the current directory, then `foo.tex` compiles fine and looks as intended.  Sorry for the oversight!

**Comment by moewew** [comment]
Good.

If things work as expected in your actual document (minus the month sorting) we can close this.
